### ISSUE TITLE
Unable To Set RequestTemplate On api-gateway-sqs Construct

### ISSUE THREAD

**Issue by mam8cc** [awslabs/aws-solutions-constructs#69]
Attempting to create an API Gateway integrated to an SQS Queue will allow you to set the `createRequestTemplate` but it appears to not honor the value set in the `ApiGatewayToSqs` props.  You can see [here](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-apigateway-sqs/lib/index.ts#L138) that it is only using the template defined on [line 30](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/aws-apigateway-sqs/lib/index.ts#L130). 

I would like to set the request template because my SQS queue is FIFO and I need to set the `MessageGroupId`.

### Reproduction Steps

```
import * as cdk from '@aws-cdk/core';
import { ApiGatewayToSqs } from '@aws-solutions-constructs/aws-apigateway-sqs';

export class ShopifyInfraStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const apiSqsIntegration = new ApiGatewayToSqs(this, 'sqsApiIntegration', {
      deployDeadLetterQueue: true,
      queueProps: {
        fifo: true
      },
      maxReceiveCount: 10,
      allowCreateOperation: true,
      createRequestTemplate: '"Action=SendMessage&MessageBody=$util.urlEncode(\"$input.body\")&MessageGroupId=$input.json(\"$.fooId\")"',
      apiGatewayProps: {
        deploy: true
      }
    });
  }
}

```
### Error Log
There is no error, and the stack deploy successfully however in the outputted template, the `createRequestTemplate` is not reflective of my configuration.

```
  sqsApiIntegrationRestApiPOSTC60EA528:
    Type: AWS::ApiGateway::Method
    Properties:
      ...
      Integration:
        ...
        RequestParameters:
          integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
        RequestTemplates:
          application/json: Action=SendMessage&MessageBody=$util.urlEncode("$input.body")
```

### Environment

  - **CDK CLI Version:** 1.63.0 (build 7a68125)
  - **CDK Framework Version:** 1.63.0
  - **AWS Solutions Constructs Version     :** 1.63.0
  - **OS                   :** macOs Catalina 10.15.1
  - **Language             :** TypeScript

### Other

--- 

This is :bug: Bug Report
